spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}
spring.profiles.include:
  - db
  - cors

server.port: 7000

spring:
  main:
    allow-bean-definition-overriding: true
  output.ansi.enabled: always
  data.web.pageable.default-page-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: ${datasource.driver-class-name}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
